# =========================
# Application
# =========================
spring.application.name=finance_tracker

# =========================
# Database
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/FinanceTrackerDatabase?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA / Hibernate
# =========================
spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=update

# Development
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# Jackson
# =========================
spring.jackson.mapper.accept-case-insensitive-enums=true

# =========================
# JWT
# =========================
jwt.secret=JWT_SECRET_HERE
jwt.duration=86400000

# =========================
# Server
# =========================
server.port=8080

# =========================
# Allowed origin
# =========================
app.cors.allowed-origin=http://localhost:5173

# =========================
# Swagger / OpenAPI
# =========================
springdoc.api-docs.path=/api-docs

# Better error messages for validation
server.error.include-message=always

# Nice colored console logs
spring.output.ansi.enabled=always

logging.level.org.springframework.security=DEBUG